title: Cornell Security
email: ""
description: >-
  Cybersecurity research, portfolio and analysis site of Norris Cornell,
  focused on critical infrastructure, signal trust, and cyber‑defense.

baseurl: ""
url: "https://www.cornellsecurity.com"

markdown: kramdown
theme: null
plugins: []
permalink: pretty

github_username: samson-2369
linkedin_username: norriscornell

collections:
  research:
    output: true
    permalink: /research/:title/
  projects:
    output: true
    permalink: /projects/:title/
  presentations:
    output: true
    permalink: /presentations/:title/

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "paper"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "presentations"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"