
title: Cornell Security
description: Cybersecurity research and portfolio of Norris Cornell
baseurl: ""
url: "https://www.cornellsecurity.com"

markdown: kramdown
theme: null
permalink: pretty

collections:
  research:
    output: true
    permalink: /research/:title/

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: paper
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default
